[package]
name = 'deppatcher'
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.14.2"
clap = { features = ["derive"], version = "3.1.12" }
walkdir = "2.3.2"
toml_edit = "0.14.2"
itertools = "0.10.3"
jrsonnet-evaluator = { git = "https://github.com/CertainLach/jrsonnet", branch = "gcmodule" }
jrsonnet-cli = { git = "https://github.com/CertainLach/jrsonnet", branch = "gcmodule" }
gcmodule = { git = "https://github.com/CertainLach/gcmodule", branch = "jrsonnet" }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
