[package]
name = "deppatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-lock = { version = "7.0.1", features = ["dependency-tree"] }
cargo_metadata = "*"
thiserror = "1.0.30"
clap = { version = "3.1.12", features = ["derive"] }
walkdir = "2.3.2"
toml_edit = "0.14.2"
itertools = "0.10.3"
jrsonnet-evaluator = {git = "https://github.com/CertainLach/jrsonnet.git", branch = "gcmodule"}
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
